"""ajoute numero_whatsapp et seuil_pertinence a Business

Revision ID: 2a5396cd649d
Revises: b3b6cd5fc67b
Create Date: 2026-07-14 14:23:57.525533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5396cd649d'
down_revision: Union[str, Sequence[str], None] = 'b3b6cd5fc67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('numero_whatsapp', sa.String(length=32), nullable=False))
    op.add_column('businesses', sa.Column('seuil_pertinence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'seuil_pertinence')
    op.drop_column('businesses', 'numero_whatsapp')
    # ### end Alembic commands ###
