"""schema initial (§4)

Revision ID: b3b6cd5fc67b
Revises: 
Create Date: 2026-07-14 14:10:52.823858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b6cd5fc67b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('langue_dominante', sa.String(length=8), nullable=False),
    sa.Column('rails_paiement_disponibles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('secteur', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('numero_paiement_momo', sa.String(length=32), nullable=False),
    sa.Column('frequence_rapport', sa.Enum('DAILY', 'WEEKLY', name='frequencerapport'), nullable=False),
    sa.Column('fuseau_horaire', sa.String(length=64), nullable=False),
    sa.Column('langue_communication', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('expression', sa.String(length=255), nullable=False),
    sa.Column('signification', sa.Text(), nullable=False),
    sa.Column('exemple_usage', sa.Text(), nullable=True),
    sa.Column('categorie', sa.Enum('INTENTION_ACHAT', 'QUESTION', 'NEGOCIATION', 'AUTRE', name='glossarycategorie'), nullable=False),
    sa.Column('source', sa.Enum('CURATION_MANUELLE', 'REMONTEE_PILOTE', name='glossarysource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('FACEBOOK_GROUP', 'WHATSAPP_GROUP', 'TIKTOK_OWN', 'GOOGLE_SEARCH', name='channeltype'), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('identifiant_externe', sa.String(length=255), nullable=False),
    sa.Column('statut_connexion', sa.Enum('CONNECTE', 'DECONNECTE', 'ERREUR', name='statutconnexion'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('mots_cles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('zone_geo_cible', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('periode_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periode_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('envoye_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINEE', name='statutlive'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('texte_source', sa.Text(), nullable=False),
    sa.Column('url_source', sa.String(length=1024), nullable=True),
    sa.Column('auteur', sa.String(length=255), nullable=True),
    sa.Column('langue_detectee', sa.Enum('FR', 'EN', 'MIXTE', name='languedetectee'), nullable=False),
    sa.Column('expressions_argot_matchees', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('score_pertinence', sa.Float(), nullable=False),
    sa.Column('score_confiance_linguistique', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'ENVOYE_AU_RAPPORT', 'JUGE_PERTINENT', 'JUGE_NON_PERTINENT', 'INCERTAIN', name='statutsignal'), nullable=False),
    sa.Column('date_detection', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_session_id', sa.Uuid(), nullable=False),
    sa.Column('auteur', sa.String(length=255), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'EN_FILE', 'RESERVE', 'EXPIRE', 'CONFIRME', name='statutcomment'), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('live_comment_id', sa.Uuid(), nullable=False),
    sa.Column('article_ref', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PAIEMENT_DEMANDE', 'CONFIRMEE', 'EXPIREE', 'LIBEREE', name='statutreservation'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_comment_id'], ['live_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('rail', sa.Enum('MOMO', 'ORANGE_MONEY', name='railpaiement'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('statut', sa.Enum('INITIEE', 'CONFIRMEE', 'ECHOUEE', 'EXPIREE', name='statuttransaction'), nullable=False),
    sa.Column('reference_externe', sa.String(length=255), nullable=True),
    sa.Column('webhook_recu_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('reservations')
    op.drop_table('live_comments')
    op.drop_table('signals')
    op.drop_table('live_sessions')
    op.drop_table('reports')
    op.drop_table('offers')
    op.drop_table('channels')
    op.drop_table('glossary_entries')
    op.drop_table('businesses')
    op.drop_table('countries')
    # ### end Alembic commands ###

    # Alembic n'auto-genere pas la suppression des types ENUM Postgres
    # natifs (ils ne sont pas rattaches a une table) : a faire explicitement,
    # sinon un downgrade puis upgrade echoue avec "type already exists".
    bind = op.get_bind()
    for enum_name in (
        'frequencerapport',
        'glossarycategorie',
        'glossarysource',
        'channeltype',
        'statutconnexion',
        'statutlive',
        'languedetectee',
        'statutsignal',
        'statutcomment',
        'statutreservation',
        'railpaiement',
        'statuttransaction',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
