"""ajoute catalogue produit et commission live tiktok

Revision ID: c0a3b3880f3c
Revises: 2a5396cd649d
Create Date: 2026-07-14 15:14:05.442690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a3b3880f3c'
down_revision: Union[str, Sequence[str], None] = '2a5396cd649d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('prix', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'reference', name='uq_products_business_reference')
    )
    op.add_column('transactions', sa.Column('commission_montant', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'commission_montant')
    op.drop_table('products')
    # ### end Alembic commands ###
